### PR TITLE
Added Counter section

### PR DESCRIPTION
**Pull request by im-gozmit**
Added counter section and a global.css file for its working.
Please review the pull request.

### CODE REVIEW

**Comment by Saichethan** [comment]
Because of our limited time we are merging it with out checking but make sure you test it once in your local machine and then open a PR.
Great if you already did the same!

**Comment by Saichethan** [comment]
@im-gozmit I have merged your PR but it's static please work on counter animation

**Comment by im-gozmit** [comment]
Hey @Saichethan , thanks for reviewing and merging I will work with counter's animation in 2-3 days, quite busy in some other works.  Hope you get that :)

**Comment by Saichethan** [comment]
Sure!

**Pull request merged**
